name: Report
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: |
          make install
      - name: Run script
        run: | 
          python scripts/descstats.py
